// Generated by Apple Swift version 2.1 (swiftlang-700.1.101.6 clang-700.1.76)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import AVFoundation;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC4Surf25AcknowledgeViewController")
@interface AcknowledgeViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class BarcodeScanViewController;


/// The tunnel delegate protocol.
SWIFT_PROTOCOL("_TtP4Surf19BarcodeScanDelegate_")
@protocol BarcodeScanDelegate
- (void)barcodeScanDidScan:(BarcodeScanViewController * __nonnull)controller configString:(NSString * __nonnull)configString;
- (void)barcodeScanCancelScan:(BarcodeScanViewController * __nonnull)controller;
@end

@class KKSocks;
@protocol AddEditDelegate;
@class NSMutableArray;
@class UISegmentedControl;
@class UIStoryboardSegue;
@class TextFieldCell;

SWIFT_CLASS("_TtC4Surf17AddEditController")
@interface AddEditController : UITableViewController <BarcodeScanDelegate>
@property (nonatomic) NSInteger numberOfSetting;
@property (nonatomic) BOOL useCamera;
@property (nonatomic, strong) KKSocks * __nonnull config;
@property (nonatomic, strong) id <AddEditDelegate> __nullable delegate;
@property (nonatomic) BOOL typeHttp;
@property (nonatomic, strong) NSMutableArray * __nonnull textFields;
@property (nonatomic, weak) IBOutlet TextFieldCell * __null_unspecified nameCell;
@property (nonatomic, weak) IBOutlet TextFieldCell * __null_unspecified addressCell;
@property (nonatomic, weak) IBOutlet TextFieldCell * __null_unspecified portCell;
@property (nonatomic, weak) IBOutlet TextFieldCell * __null_unspecified passwdCell;
@property (nonatomic, weak) IBOutlet TextFieldCell * __null_unspecified methodCell;
- (void)viewDidLoad;
- (void)loadConfig;
- (void)valueChanged:(UISegmentedControl * __nonnull)sender;
- (void)saveConfig:(id __nonnull)sender;
- (IBAction)useBarcode:(id __nonnull)sender;
- (void)barcodeScanDidScan:(BarcodeScanViewController * __nonnull)controller configString:(NSString * __nonnull)configString;
- (void)barcodeScanCancelScan:(BarcodeScanViewController * __nonnull)controller;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



/// The tunnel delegate protocol.
SWIFT_PROTOCOL("_TtP4Surf15AddEditDelegate_")
@protocol AddEditDelegate
- (void)addConfig:(AddEditController * __nonnull)controller config:(KKSocks * __nonnull)config;
@end

@class UIWindow;
@class UIApplication;
@class NSObject;

SWIFT_CLASS("_TtC4Surf11AppDelegate")
@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (nonatomic, strong) UIWindow * __nullable window;
- (BOOL)application:(UIApplication * __nonnull)application didFinishLaunchingWithOptions:(NSDictionary * __nullable)launchOptions;
- (void)applicationWillResignActive:(UIApplication * __nonnull)application;
- (void)applicationDidEnterBackground:(UIApplication * __nonnull)application;
- (void)applicationWillEnterForeground:(UIApplication * __nonnull)application;
- (void)applicationDidBecomeActive:(UIApplication * __nonnull)application;
- (void)applicationWillTerminate:(UIApplication * __nonnull)application;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class AVCaptureSession;
@class AVCaptureVideoPreviewLayer;
@class AVCaptureOutput;
@class AVCaptureConnection;

SWIFT_CLASS("_TtC4Surf25BarcodeScanViewController")
@interface BarcodeScanViewController : UIViewController <AVCaptureMetadataOutputObjectsDelegate>
@property (nonatomic, readonly, copy) NSString * __nonnull kScanQRCodeQueueName;
@property (nonatomic, strong) AVCaptureSession * __nullable captureSession;
@property (nonatomic, strong) AVCaptureVideoPreviewLayer * __nullable videoPreviewLayer;
@property (nonatomic) BOOL useCamera;
@property (nonatomic, strong) id <BarcodeScanDelegate> __nullable delegate;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (IBAction)cancleAction:(id __nonnull)sender;
- (BOOL)startReading;
- (void)stopReading;
- (void)captureOutput:(AVCaptureOutput * __null_unspecified)captureOutput didOutputMetadataObjects:(NSArray * __null_unspecified)metadataObjects fromConnection:(AVCaptureConnection * __null_unspecified)connection;
- (void)reportScanResult:(NSString * __null_unspecified)result;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4Surf9DataShare")
@interface DataShare : NSObject
+ (BOOL)save:(KKSocks * __nonnull)sock;
+ (NSString * __nonnull)configPath;
+ (KKSocks * __nonnull)readConfig;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC4Surf23HelpTableViewController")
@interface HelpTableViewController : UITableViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSURL;
@class UITextView;

SWIFT_CLASS("_TtC4Surf21LogFileViewController")
@interface LogFileViewController : UIViewController
@property (nonatomic, strong) NSURL * __nullable filePath;
@property (nonatomic, weak) IBOutlet UITextView * __nullable textView;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableView;
@class NSIndexPath;
@class UITableViewCell;

SWIFT_CLASS("_TtC4Surf26LogListTableViewController")
@interface LogListTableViewController : UITableViewController
@property (nonatomic, copy) NSArray<NSString *> * __nonnull fileList;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)findFiles;
- (void)didReceiveMemoryWarning;
- (NSInteger)numberOfSectionsInTableView:(UITableView * __nonnull)tableView;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NEVPNManager;
@class UIButton;

SWIFT_CLASS("_TtC4Surf23ProxyListViewController")
@interface ProxyListViewController : UITableViewController <AddEditDelegate>

/// The target VPN configuration.
@property (nonatomic, strong) NEVPNManager * __nonnull targetManager;
@property (nonatomic, strong) NEVPNManager * __nullable configManage;

/// A list of NEVPNManager objects for the packet tunnel configurations.
@property (nonatomic, copy) NSArray<NEVPNManager *> * __nonnull managers;
@property (nonatomic, weak) UIButton * __nullable startStopButton;
@property (nonatomic, strong) NSMutableArray * __nonnull proxyList;
@property (nonatomic, strong) NSIndexPath * __nullable selectPath;
@property (nonatomic, strong) NSURL * __nonnull applicationDocumentsDirectory;
- (void)loadProxys;

/// Unwind segue handler.
- (IBAction)handleUnwind:(UIStoryboardSegue * __nonnull)sender;
- (void)saveProxys;

/// Handle the event where the view is being hidden.
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidLoad;
- (void)findUsedConfig;

/// Handle the event of the view being displayed.
- (void)viewWillAppear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (void)setEditing:(BOOL)editing animated:(BOOL)animated;
- (NSInteger)numberOfSectionsInTableView:(UITableView * __nonnull)tableView;
- (NSInteger)tableView:(UITableView * __nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (IBAction)startConnect:(id __nonnull)sender;
- (UITableViewCell * __nonnull)tableView:(UITableView * __nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)updateCell:(UITableViewCell * __nonnull)cell indexPath:(NSIndexPath * __nonnull)indexPath;
- (BOOL)tableView:(UITableView * __nonnull)tableView canEditRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (UITableViewCellEditingStyle)tableView:(UITableView * __nonnull)tableView editingStyleForRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)tableView:(UITableView * __nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)saveConfig;
- (void)tableView:(UITableView * __nonnull)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath * __nonnull)indexPath;
- (void)addConfig:(AddEditController * __nonnull)controller config:(KKSocks * __nonnull)config;
- (void)prepareForSegue:(UIStoryboardSegue * __nonnull)segue sender:(id __nullable)sender;
- (nonnull instancetype)initWithStyle:(UITableViewStyle)style OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ProxyListViewController (SWIFT_EXTENSION(Surf))
- (void)setTargetManager:(NEVPNManager * __nullable)manager title:(NSString * __nullable)title;

/// Re-load all of the packet tunnel configurations from the Network Extension preferences
- (void)reloadManagers;

/// Register for configuration change notifications.
- (void)registerStatus;
- (void)observeStatus;

/// De-register for configuration change notifications.
- (void)stopObservingStatus;
- (void)xpc;

/// Handle the user toggling the "enabled" switch.
- (IBAction)enabledToggled;

/// Handle the user toggling the "VPN" switch.
- (IBAction)startStopToggled:(id __nonnull)sender;
@end


SWIFT_CLASS("_TtC4Surf20SecondViewController")
@interface SecondViewController : UIViewController
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;
- (nonnull instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Socks")
@interface KKSocks : NSObject <NSCoding>
@property (nonatomic, copy) NSString * __nullable proxyName;
@property (nonatomic, copy) NSString * __nullable serverAddress;
@property (nonatomic, copy) NSString * __nullable serverPort;
@property (nonatomic, copy) NSString * __nullable password;
@property (nonatomic, copy) NSString * __nullable method;
@property (nonatomic, copy) NSString * __nullable serverType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)encodeWithCoder:(NSCoder * __nonnull)aCoder;
@end

@class UITextField;
@class UILabel;

SWIFT_CLASS("_TtC4Surf13TextFieldCell")
@interface TextFieldCell : UITableViewCell <UITextFieldDelegate>
@property (nonatomic, weak) IBOutlet UITextField * __null_unspecified textField;
@property (nonatomic, weak) IBOutlet UILabel * __null_unspecified cellLabel;
@property (nonatomic, copy) void (^ __nullable valueChanged)(UITextField * __nonnull);
- (void)textFieldDidEndEditing:(UITextField * __nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * __nonnull)textField;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * __nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
